(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ag-reuse-buffers t)
 '(company-idle-delay 3)
 '(compilation-scroll-output t)
 '(eat-term-name "eat-256color")
 '(eglot-ignored-server-capabilities '(:inlayHintProvider))
 '(eldoc-echo-area-prefer-doc-buffer t)
 '(eldoc-echo-area-use-multiline-p nil)
 '(js2-auto-indent-p nil)
 '(js2-basic-offset 2)
 '(js2-cleanup-whitespace nil)
 '(js2-indent-on-enter-key nil)
 '(js2-mirror-mode nil)
 '(markdown-code-lang-modes
   '(("rust" . rust-mode)
     ("haskell" . haskell-mode)
     ("ocaml" . tuareg-mode)
     ("elisp" . emacs-lisp-mode)
     ("ditaa" . artist-mode)
     ("asymptote" . asy-mode)
     ("dot" . fundamental-mode)
     ("sqlite" . sql-mode)
     ("calc" . fundamental-mode)
     ("C" . c-mode)
     ("cpp" . c++-mode)
     ("C++" . c++-mode)
     ("screen" . shell-script-mode)
     ("shell" . sh-mode)
     ("bash" . sh-mode)))
 '(ns-command-modifier 'meta))
;; The following 16-color palette is recommended.
;; It's based on Colorized Light, with most of shades of gray replaced
;; with bright colors to use as backgrounds.
;; Terminal background: #fdf6e4 (same as brightwhite)
;;          foreground: #657b83
;;          cursor:     #b1b5d8 (brightmagenta, 40% opacity)
;; [
;;  "#043642",
;;  "#b12621",
;;  "#1f892b",
;;  "#b68900",
;;  "#268bd2",
;;  "#94245c",
;;  "#249482",
;;  "#eee8d6",
;;  "#93a1a1",
;;  "#c7692b",
;;  "#eef9c2",
;;  "#ffeac7",
;;  "#dfe3ec",
;;  "#3657cb",
;;  "#ddf3ed",
;;  "#fdf6e4"
;; ]
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-bright-black ((t (:inherit ansi-color-black :bold t))))
 '(ansi-color-bright-blue ((t (:inherit ansi-color-blue :bold t))))
 '(ansi-color-bright-cyan ((t (:inherit ansi-color-cyan :bold t))))
 '(ansi-color-bright-green ((t (:inherit ansi-color-green :bold t))))
 '(ansi-color-bright-magenta ((t (:inherit ansi-color-magenta :bold t))))
 '(ansi-color-bright-red ((t (:inherit ansi-color-red :bold t))))
 '(ansi-color-bright-white ((t (:inherit ansi-color-white :bold t))))
 '(ansi-color-bright-yellow ((t (:inherit ansi-color-yellow :bold t))))
 '(compilation-mode-line-fail ((t (:inherit error))))
 '(compilation-mode-line-run ((t (:foreground "blue" :bold t))))
 '(completions-common-part ((t (:foreground "blue"))))
 '(cua-global-mark ((t (:inherit match))))
 '(cua-rectangle ((t (:inherit region))))
 '(custom-face-tag ((t (:foreground "brightblack"))))
 '(custom-group-tag ((t (:inherit custom-face-tag))))
 '(custom-group-tag1 ((t (:inherit custom-face-tag))))
 '(diff-added ((t (:inherit diff-changed :foreground "green"))))
 '(diff-context ((t (:foreground "brightblack"))))
 '(diff-error ((t (:inherit error))))
 '(diff-file-header ((t (:foreground "black"))))
 '(diff-header ((t (:background "brightyellow"))))
 '(diff-refine-added ((t (:inherit diff-added :background "brightgreen"))))
 '(diff-refine-changed ((t (:inherit diff-changed :bold t))))
 '(diff-refine-removed ((t (:inherit diff-removed :background "brightblue"))))
 '(diff-removed ((t (:inherit diff-changed :foreground "blue"))))
 '(eat-term-color-10 ((t (:inherit ansi-color-green :bold t))))
 '(eat-term-color-100 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-101 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-102 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-103 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-104 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-105 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-106 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-107 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-108 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-109 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-11 ((t (:inherit ansi-color-yellow :bold t))))
 '(eat-term-color-110 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-111 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-112 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-113 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-114 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-115 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-116 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-117 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-118 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-119 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-12 ((t (:inherit ansi-color-blue :bold t))))
 '(eat-term-color-120 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-121 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-122 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-123 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-124 ((t (:background "red" :foreground "red"))))
 '(eat-term-color-125 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-126 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-127 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-128 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-129 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-13 ((t (:inherit ansi-color-magenta :bold t))))
 '(eat-term-color-130 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-131 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-132 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-133 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-134 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-135 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-136 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-137 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-138 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-139 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-14 ((t (:inherit ansi-color-cyan :bold t))))
 '(eat-term-color-140 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-141 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-142 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-143 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-144 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-145 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-146 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-147 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-148 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-149 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-15 ((t (:inherit ansi-color-white :bold t))))
 '(eat-term-color-150 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-151 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-152 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-153 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-154 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-155 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-156 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-157 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-158 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-159 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-16 ((t (:background "black" :foreground "black"))))
 '(eat-term-color-160 ((t (:background "red" :foreground "red"))))
 '(eat-term-color-161 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-162 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-163 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-164 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-165 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-166 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-167 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-168 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-169 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-17 ((t (:background "black" :foreground "black"))))
 '(eat-term-color-170 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-171 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-172 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-173 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-174 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-175 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-176 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-177 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-178 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-179 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-18 ((t (:background "black" :foreground "black"))))
 '(eat-term-color-180 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-181 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-182 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-183 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-184 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-185 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-186 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-187 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-188 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-189 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-19 ((t (:background "black" :foreground "black"))))
 '(eat-term-color-190 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-191 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-192 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-193 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-194 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-195 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-196 ((t (:background "red" :foreground "red"))))
 '(eat-term-color-197 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-198 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-199 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-20 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-200 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-201 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-202 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-203 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-204 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-205 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-206 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-207 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-208 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-209 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-21 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-210 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-211 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-212 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-213 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-214 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-215 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-216 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-217 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-218 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-219 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-22 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-220 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-221 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-222 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-223 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-224 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-225 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-226 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-227 ((t (:background "yellow" :foreground "yellow"))))
 '(eat-term-color-228 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-229 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-23 ((t (:background "black" :foreground "black"))))
 '(eat-term-color-230 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-231 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-232 ((t (:foreground "brightwhite" :background "brightwhite"))))
 '(eat-term-color-233 ((t (:foreground "brightwhite" :background "brightwhite"))))
 '(eat-term-color-234 ((t (:foreground "brightwhite" :background "brightwhite"))))
 '(eat-term-color-235 ((t (:foreground "brightwhite" :background "brightwhite"))))
 '(eat-term-color-236 ((t (:foreground "brightwhite" :background "brightwhite"))))
 '(eat-term-color-237 ((t (:foreground "brightwhite" :background "brightwhite"))))
 '(eat-term-color-238 ((t (:foreground "white" :background "white"))))
 '(eat-term-color-239 ((t (:foreground "white" :background "white"))))
 '(eat-term-color-24 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-240 ((t (:foreground "white" :background "white"))))
 '(eat-term-color-241 ((t (:foreground "white" :background "white"))))
 '(eat-term-color-242 ((t (:foreground "white" :background "white"))))
 '(eat-term-color-243 ((t (:foreground "white" :background "white"))))
 '(eat-term-color-244 ((t (:foreground "brightblack" :background "brightblack"))))
 '(eat-term-color-245 ((t (:foreground "brightblack" :background "brightblack"))))
 '(eat-term-color-246 ((t (:foreground "brightblack" :background "brightblack"))))
 '(eat-term-color-247 ((t (:foreground "brightblack" :background "brightblack"))))
 '(eat-term-color-248 ((t (:foreground "brightblack" :background "brightblack"))))
 '(eat-term-color-249 ((t (:foreground "brightblack" :background "brightblack"))))
 '(eat-term-color-25 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-250 ((t (:foreground "black" :background "black"))))
 '(eat-term-color-251 ((t (:foreground "black" :background "black"))))
 '(eat-term-color-252 ((t (:foreground "black" :background "black"))))
 '(eat-term-color-253 ((t (:foreground "black" :background "black"))))
 '(eat-term-color-254 ((t (:foreground "black" :background "black"))))
 '(eat-term-color-255 ((t (:foreground "black" :background "black"))))
 '(eat-term-color-26 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-27 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-28 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-29 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-30 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-31 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-32 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-33 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-34 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-35 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-36 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-37 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-38 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-39 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-40 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-41 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-42 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-43 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-44 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-45 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-46 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-47 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-48 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-49 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-50 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-51 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-52 ((t (:background "red" :foreground "red"))))
 '(eat-term-color-53 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-54 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-55 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-56 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-57 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-58 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-59 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-60 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-61 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-62 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-63 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-64 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-65 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-66 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-67 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-68 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-69 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-70 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-71 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-72 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-73 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-74 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-75 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-76 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-77 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-78 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-79 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-8 ((t (:inherit ansi-color-black :bold t))))
 '(eat-term-color-80 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-81 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-82 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-83 ((t (:background "green" :foreground "green"))))
 '(eat-term-color-84 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-85 ((t (:background "cyan" :foreground "cyan"))))
 '(eat-term-color-86 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-87 ((t (:background "blue" :foreground "blue"))))
 '(eat-term-color-88 ((t (:background "red" :foreground "red"))))
 '(eat-term-color-89 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-9 ((t (:inherit ansi-color-red :bold t))))
 '(eat-term-color-90 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-91 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-92 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-93 ((t (:background "magenta" :foreground "magenta"))))
 '(eat-term-color-94 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-95 ((t (:background "brightred" :foreground "brightred"))))
 '(eat-term-color-96 ((t (:background "brightblack" :foreground "brightblack"))))
 '(eat-term-color-97 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-98 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(eat-term-color-99 ((t (:background "brightmagenta" :foreground "brightmagenta"))))
 '(ediff-current-diff-A ((t (:background "brightblue"))))
 '(ediff-current-diff-Ancestor ((t (:background "brightred" :foreground "brightwhite"))))
 '(ediff-current-diff-B ((t (:background "brightyellow"))))
 '(ediff-current-diff-C ((t (:background "brightgreen"))))
 '(ediff-even-diff-A ((t (:inherit ediff-current-diff-A))))
 '(ediff-even-diff-Ancestor ((t (:inherit ediff-current-diff-Ancestor))))
 '(ediff-even-diff-B ((t (:inherit ediff-current-diff-B))))
 '(ediff-even-diff-C ((t (:inherit ediff-current-diff-C))))
 '(ediff-fine-diff-A ((t (:inherit ediff-current-diff-A :bold t))))
 '(ediff-fine-diff-Ancestor ((t (:inherit ediff-current-diff-Ancestor :bold t))))
 '(ediff-fine-diff-B ((t (:inherit ediff-current-diff-B :bold t))))
 '(ediff-fine-diff-C ((t (:inherit ediff-current-diff-C :bold t))))
 '(ediff-odd-diff-A ((t (:inherit ediff-current-diff-A))))
 '(ediff-odd-diff-Ancestor ((t (:inherit ediff-current-diff-Ancestor))))
 '(ediff-odd-diff-B ((t (:inherit ediff-current-diff-B))))
 '(ediff-odd-diff-C ((t (:inherit ediff-current-diff-C))))
 '(eglot-highlight-symbol-face ((t (:inherit underline))))
 '(error ((t (:foreground "red" :bold t))))
 '(eww-form-text ((t (:inherit widget-field))))
 '(font-lock-builtin-face ((t (:foreground "blue"))))
 '(font-lock-comment-face ((t (:foreground "brightblack"))))
 '(font-lock-constant-face ((t (:foreground "cyan"))))
 '(font-lock-function-name-face ((t (:bold t))))
 '(font-lock-keyword-face ((t (:foreground "magenta"))))
 '(font-lock-preprocessor-face ((t (:foreground "black"))))
 '(font-lock-string-face ((t (:foreground "yellow"))))
 '(font-lock-type-face ((t (:foreground "green"))))
 '(font-lock-variable-name-face ((t (:foreground "blue"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(gptel-context-highlight-face ((t (:inherit secondary-selection))))
 '(header-line ((t (:inherit mode-line-inactive))))
 '(header-line-highlight ((t (:inherit mode-line))))
 '(help-key-binding ((t (:bold t))))
 '(hi-yellow ((t (:background "brightyellow"))))
 '(highlight ((t (:background "white"))))
 '(isearch ((t (:inherit match))))
 '(isearch-fail ((t (:background "red" :foreground "brightwhite"))))
 '(langtool-correction-face ((t (:background "brightyellow"))))
 '(langtool-errline ((t (:inherit error :underline t))))
 '(lazy-highlight ((t (:background "brightyellow"))))
 '(link ((t (:foreground "blue" :underline t))))
 '(magit-blame-heading ((t (:inherit diff-header))))
 '(magit-branch-local ((t (:inherit default :bold t))))
 '(magit-diff-added ((t (:inherit diff-added))))
 '(magit-diff-added-highlight ((t (:inherit diff-added :background "brightgreen"))))
 '(magit-diff-base ((t (:foreground "yellow"))))
 '(magit-diff-base-highlight ((t (:inherit magit-diff-base :background "brightyellow"))))
 '(magit-diff-context ((t (:inherit diff-context))))
 '(magit-diff-context-highlight ((t (:inherit diff-context :background "white"))))
 '(magit-diff-file-heading ((t (:inherit diff-file-header))))
 '(magit-diff-hunk-heading ((t (:inherit diff-header))))
 '(magit-diff-refine-changed ((t (:inherit diff-changed :bold t))))
 '(magit-diff-removed ((t (:inherit diff-removed))))
 '(magit-diff-removed-highlight ((t (:inherit diff-removed :background "brightblue"))))
 '(magit-header-line ((t (:inherit header-line :bold t))))
 '(magit-section-highlight ((t (:inherit highlight))))
 '(match ((t (:background "brightgreen"))))
 '(minibuffer-prompt ((t (:foreground "brightmagenta"))))
 '(mode-line ((t (:foreground "white" :background "black"))))
 '(mode-line-inactive ((t (:foreground "black" :background "white"))))
 '(region ((t (:background "brightcyan"))))
 '(secondary-selection ((t (:background "brightblue"))))
 '(shadow ((t (:foreground "brightblack"))))
 '(show-paren-match ((t (:bold t))))
 '(show-paren-mismatch ((t (:inherit isearch-fail))))
 '(smerge-base ((t (:background "brightyellow"))))
 '(smerge-lower ((t (:background "brightgreen"))))
 '(smerge-markers ((t (:background "brightred" :foreground "brightwhite"))))
 '(smerge-refined-added ((t (:inherit diff-added :bold t))))
 '(smerge-refined-change ((t (:inherit diff-changed))) t)
 '(smerge-refined-changed ((t (:inherit diff-changed))))
 '(smerge-refined-removed ((t (:inherit diff-removed :bold t))))
 '(smerge-upper ((t (:background "brightblue"))))
 '(transient-key-exit ((t (:foreground "brightmagenta"))))
 '(transient-key-return ((t (:foreground "brightred"))))
 '(transient-key-stay ((t (:foreground "brightmagenta"))))
 '(transient-unreachable-key ((t (:foreground "white"))))
 '(vertical-border ((t (:inherit mode-line-inactive))))
 '(warning ((t (:foreground "brightred" :bold t))))
 '(which-func ((t (:inherit header-line))))
 '(whitespace-big-indent ((t (:inherit whitespace-tab))))
 '(whitespace-tab ((t (:background "brightred" :foreground "white"))))
 '(widget-field ((t (:background "brightcyan" :foreground "black"))))
 '(widget-single-line-field ((t (:background "brightblue" :foreground "black")))))
