# -----------------------------------------------------------------------------
# Core Prefix, Escape Key, Clipboard
# -----------------------------------------------------------------------------
# Control-/ is the new escape key
unbind C-b
# Note: If 'C-/' doesn't register depending on your host terminal emulator,
# use 'C-_'
set -g prefix 'C-_'
# To send C-/ to emacs, type C-/ /
bind / send-prefix

# CRITICAL FOR EMACS: Remove the escape key delay
# Without this, hitting ESC in Emacs will pause for 500ms
set -sg escape-time 0

# Enable terminal apps to use the clipboard
set -s set-clipboard on

# -----------------------------------------------------------------------------
# Display, Colors & Environment
# -----------------------------------------------------------------------------
# Use 16 colors to better control applications color scheme
set -g default-command "env -u COLORTERM $SHELL"
set -g default-terminal "screen-16color-bce"

# vbell off
set -g visual-bell off
set -g bell-action none

# defscrollback 100000
set -g history-limit 100000

# -----------------------------------------------------------------------------
# Status Line (Hardstatus equivalent)
# -----------------------------------------------------------------------------
# hardstatus alwaysfirstline "%{kw}%h%=%0c"
set -g status-position top
set -g status-style bg=white,fg=black
# The Left Side: Display the Pane Title (#T) which captures the OSC sequence.
# tmux defaults the left side to a maximum of 10 characters, increase this limit.
set -g status-left-length 150
set -g status-left "#T "
# The Center: Show window names
setw -g window-status-format " #W "
setw -g window-status-current-format " [#W] "
# The Right Side: Display the time
set -g status-right "%H:%M"

# -----------------------------------------------------------------------------
# Custom Key Bindings
# -----------------------------------------------------------------------------
# C-/ C-c copies the paste buffer to X clipboard
# This saves the tmux buffer and pipes it directly to xclip
bind C-c run-shell "tmux save-buffer - | xclip -in -selection clipboard"

# C-/ C-k clears the terminal display and the scrollback buffer
bind C-k send-keys C-l \; clear-history
