#!/bin/bash

# Ensure we use an absolute path with a trailing slash for default-directory
TARGET_DIR="$PWD/site-lisp/"

emacs --batch --eval "
  (let ((default-directory \"$TARGET_DIR\"))
    ;; Add the base site-lisp directory to the load-path
    (add-to-list 'load-path default-directory)
    ;; Automatically discover and add all subdirectories
    (normal-top-level-add-subdirs-to-load-path)
    ;; Recompile the directory (0 forces recompilation of all files)
    (byte-recompile-directory default-directory 0))
"
